### ISSUE TITLE
Proposal: standard (portaudio) as default setting

### ISSUE THREAD

**Issue by pmuelle2** [zhdk/tpf-client#7]
Wouldn't it make sense if the default setting for the audio system (when e.g. opening tpf-party for the first time) is "standard (portaudio)" instead of Jack? 
This would result in most cases that the signal from the local gear might immediately show in the tpf-party's level.
As tpf-party is aimed at easy use, this could make sense. Jack is then an audio system which can be used when Jack is installed (which is not a prerequisite for using tpf-party).

**Comment by reduzent** [comment]
I totally agree. Bad thing is, the only macOS I currently have access to is a virtual machine without any sound at all. So I can't really test my builds. I wasn't even aware that JACK backend is auto-selected. I'll surely will look into it.

**Comment by pmuelle2** [comment]
Just for your information: this is how it shows when I open the Preferences / Media (see screenshot [attached). 
<img width="538" alt="Bildschirmfoto 2021-02-15 um 17 57 54" src="https://user-images.githubusercontent.com/79091921/107974935-99810580-6fb7-11eb-81aa-e11971df54f2.png">
So Jack is not ticked, but it shows in the audio settings (no idea whether this has to do with my individual machine or with the pd patch...).

By the way, we have 4 MacBookPros, one is in Dortmund, one with Matthias, one with me - so there is a fourth one: would you like to have it? You can then try out these things...

**Comment by reduzent** [comment]
Thanks for the detailed info. I'll contact you privately regarding the MBP.

**Comment by reduzent** [comment]
Ok. Having an actual Mac with real audio helps tremendously in figuring out these things. 

tpf-party now defaults to portaudio at start.

**Comment by reduzent** [comment]
The fix got release with package tpf-party-v1.1-beta3.dmg

**Comment by pmuelle2** [comment]
Lieber Roman, du kannst einfach immer sagen, wenn du etwas brauchst, auch zB ein Interface, ich kann mich gerne um solche Sachen kümmern.
LgPatrick

Am 01.03.2021 um 12:05 schrieb Roman Haefeli <notifications@github.com>:

﻿

Ok. Having an actual Mac with real audio helps tremendously in figuring out these things.

tpf-party now defaults to portaudio at start.
